[forest]
trees = ["trees/"]                                # The directories in which your trees are stored
assets = ["assets"]                              # The directories in which your assets are stored
theme = "istheme"                         # The directory in which your theme is stored
root = "epoche-0001"
base_url = "https://suspenss.github.io/forest/"
prefixes = ["epoche", "poem", "ocmst", "sponge", "rust", "move"]
